In [39]:
import pandas as pd

In [40]:
df = pd.read_csv('train.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [41]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [42]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [43]:
dataset = df.drop(["PassengerId","SibSp","Parch","Ticket","Fare","Cabin","Embarked"],axis="columns")

In [44]:
#Filling missing values by mean
dataset['Age'].fillna(dataset['Age'].mean(),inplace=True)

In [45]:
dataset

,Survived,Pclass,Name,Sex,Age
0,0,3,"Braund, Mr. Owen Harris",male,22.000000
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000
2,1,3,"Heikkinen, Miss. Laina",female,26.000000
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000
4,0,3,"Allen, Mr. William Henry",male,35.000000
...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.000000
887,1,1,"Graham, Miss. Margaret Edith",female,19.000000
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118
889,1,1,"Behr, Mr. Karl Howell",male,26.000000
890,0,3,"Dooley, Mr. Patrick",male,32.000000

In [46]:
dataset.isnull().sum()

Survived    0
Pclass      0
Name        0
Sex         0
Age         0
dtype: int64

In [47]:
dataset.dtypes

Survived      int64
Pclass        int64
Name         object
Sex          object
Age         float64
dtype: object

In [48]:
dataset['Age'] = dataset['Age'].astype(int)

In [49]:
dataset.dtypes

Survived     int64
Pclass       int64
Name        object
Sex         object
Age          int64
dtype: object

In [50]:
from sklearn.preprocessing import LabelEncoder

In [51]:
name_n = LabelEncoder()
gender_n = LabelEncoder()

In [52]:
le_name = name_n.fit_transform(dataset['Name'])
le_gender = gender_n.fit_transform(dataset['Sex'])

In [53]:
dataset['name_n']=le_name
dataset['gender_n']=le_gender

In [54]:
dataset

,Survived,Pclass,Name,Sex,Age,name_n,gender_n
0,0,3,"Braund, Mr. Owen Harris",male,22,108,1
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,190,0
2,1,3,"Heikkinen, Miss. Laina",female,26,353,0
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,272,0
4,0,3,"Allen, Mr. William Henry",male,35,15,1
...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27,548,1
887,1,1,"Graham, Miss. Margaret Edith",female,19,303,0
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29,413,0
889,1,1,"Behr, Mr. Karl Howell",male,26,81,1
890,0,3,"Dooley, Mr. Patrick",male,32,220,1

In [55]:
encoded_data = dataset.drop(['Name','Sex'],axis='columns')

In [56]:
encoded_data

     Survived  Pclass  Age  name_n  gender_n
0           0       3   22     108         1
1           1       1   38     190         0
2           1       3   26     353         0
3           1       1   35     272         0
4           0       3   35      15         1
..        ...     ...  ...     ...       ...
886         0       2   27     548         1
887         1       1   19     303         0
888         0       3   29     413         0
889         1       1   26      81         1
890         0       3   32     220         1

[891 rows x 5 columns]

In [57]:
X = encoded_data.drop('Survived',axis='columns').values

In [58]:
X

array([[  3,  22, 108,   1],
       [  1,  38, 190,   0],
       [  3,  26, 353,   0],
       ...,
       [  3,  29, 413,   0],
       [  1,  26,  81,   1],
       [  3,  32, 220,   1]])

In [59]:
y=encoded_data.Survived.values

In [60]:
y

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0])

In [61]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=7)

In [62]:
X_test

array([[  3,  20, 617,   1],
       [  2,  21, 283,   1],
       [  3,  39, 725,   1],
       [  3,  29, 473,   1],
       [  1,  21, 490,   0],
       [  2,  38, 270,   0],
       [  3,  32, 220,   1],
       [  3,  36, 474,   1],
       [  2,  28, 593,   1],
       [  1,  56, 668,   0],
       [  2,  29, 246,   0],
       [  3,  29, 716,   1],
       [  2,  34, 219,   0],
       [  2,   8, 172,   0],
       [  3,  30, 814,   1],
       [  3,  29, 438,   1],
       [  3,  22, 749,   1],
       [  2,  29, 445,   1],
       [  3,  34, 197,   1],
       [  2,  18, 243,   1],
       [  1,  27, 345,   1],
       [  3,  21, 638,   1],
       [  1,  80,  66,   1],
       [  3,  12, 588,   1],
       [  3,  44, 433,   1],
       [  3,   9, 182,   1],
       [  2,  36,  35,   0],
       [  3,  18, 166,   1],
       [  2,  48, 538,   1],
       [  1,  29, 265,   0],
       [  2,  33, 855,   0],
       [  2,  24, 423,   0],
       [  3,  29, 603,   1],
       [  2,  34, 422,   1],
       [  3,  32, 158,   1],
       [  3,  25, 713,   1],
       [  1,  36, 144,   1],
       [  3,  33, 410,   1],
       [  3,  39,  28,   1],
       [  2,  54, 224,   1],
       [  3,  43, 371,   1],
       [  3,   4, 407,   1],
       [  3,  29, 502,   1],
       [  3,  40, 889,   1],
       [  3,  59, 184,   1],
       [  3,   9, 297,   1],
       [  3,   4, 755,   1],
       [  3,  29, 644,   1],
       [  2,  59, 754,   1],
       [  3,  30,  47,   1],
       [  3,  28, 595,   1],
       [  2,  28, 162,   0],
       [  1,  39, 805,   0],
       [  2,  25, 772,   1],
       [  3,  25, 817,   1],
       [  3,  21, 103,   1],
       [  3,   9,  26,   0],
       [  3,  51, 306,   1],
       [  3,  26, 455,   1],
       [  3,  22, 193,   0],
       [  1,  38, 385,   0],
       [  2,  39, 534,   1],
       [  3,  29, 606,   0],
       [  1,  55, 547,   1],
       [  3,  18, 660,   0],
       [  3,  20, 323,   1],
       [  2,  62, 336,   1],
       [  3,  30, 506,   0],
       [  3,  30, 123,   0],
       [  1,  50,  71,   0],
       [  1,  49, 290,   1],
       [  3,  49, 409,   1],
       [  3,  29, 720,   1],
       [  1,  28, 535,   1],
       [  2,  29, 634,   1],
       [  3,  38, 675,   1],
       [  1,  24, 723,   0],
       [  1,  56, 766,   1],
       [  3,  27, 375,   0],
       [  1,  47, 667,   1],
       [  3,  29,  99,   0],
       [  3,  29, 252,   1],
       [  3,  29, 818,   1],
       [  3,  31, 619,   0],
       [  1,  62, 785,   0],
       [  3,  30,   5,   1],
       [  3,  27, 875,   1],
       [  3,  29, 552,   0],
       [  3,  28, 198,   0],
       [  1,  47, 843,   1],
       [  3,  29, 413,   0],
       [  1,  52, 661,   1],
       [  1,  16, 485,   0],
       [  3,   9,  97,   0],
       [  3,  29, 715,   1],
       [  2,  50, 636,   0],
       [  3,  29, 527,   0],
       [  3,  30, 487,   1],
       [  1,  29, 125,   1],
       [  3,  28, 138,   1],
       [  1,  22, 163,   0],
       [  2,  27, 230,   0],
       [  3,  35, 509,   1],
       [  3,  25, 793,   1],
       [  3,  29, 849,   1],
       [  3,  19, 221,   1],
       [  3,   4, 680,   1],
       [  1,  29, 536,   0],
       [  3,  18, 231,   1],
       [  3,  43, 179,   1],
       [  3,  29, 726,   1],
       [  3,   1, 628,   1],
       [  1,  49, 462,   0],
       [  2,  50, 689,   0],
       [  3,  32, 309,   1],
       [  1,  42, 439,   1],
       [  3,  50, 706,   1],
       [  2,  18, 218,   0],
       [  2,  25, 160,   0],
       [  3,  29, 343,   1],
       [  1,  40, 741,   0],
       [  3,  29, 699,   1],
       [  3,  29, 240,   1],
       [  3,  29, 195,   1],
       [  1,  29,  69,   1],
       [  3,  19,  75,   1],
       [  1,  23, 308,   1],
       [  3,  22, 425,   1],
       [  3,  27,  29,   1],
       [  1,  44, 364,   0],
       [  3,  24, 499,   1],
       [  3,  18, 569,   1],
       [  2,  28, 206,   0],
       [  1,   2,  17,   0],
       [  3,  22, 842,   1],
       [  3,  10, 829,   0],
       [  3,  29, 627,   0],
       [  1,  29, 106,   1],
       [  3,  23, 354,   0],
       [  1,  61, 794,   1],
       [  3,  45,  64,   0],
       [  1,  26,  81,   1],
       [  1,  48, 228,   0],
       [  1,  30, 257,   1],
       [  3,  29, 712,   1],
       [  3,  29, 377,   1],
       [  2,  36, 580,   1],
       [  3,  29, 466,   0],
       [  3,  29, 790,   0],
       [  3,  24, 541,   1],
       [  3,  28, 835,   1],
       [  1,  40,  94,   1],
       [  2,  17, 468,   0],
       [  1,  16, 501,   0],
       [  3,  29, 430,   1],
       [  2,  55, 359,   0],
       [  2,  16, 278,   1],
       [  3,  31, 406,   1],
       [  1,  42, 126,   1],
       [  3,  34, 806,   1],
       [  3,  22, 177,   0],
       [  3,  39,  30,   0],
       [  3,   9, 254,   0],
       [  2,  24, 688,   0],
       [  1,  50, 264,   1],
       [  2,  23, 232,   1],
       [  3,  32, 416,   1],
       [  3,  16, 618,   1],
       [  1,  65, 620,   1],
       [  3,  61, 598,   1],
       [  3,  29, 812,   1],
       [  1,  29, 347,   1],
       [  3,   3,  42,   1],
       [  3,  15, 523,   0],
       [  1,  33, 152,   0],
       [  1,   0,  16,   1],
       [  3,  29, 692,   1],
       [  3,  29, 250,   1],
       [  2,  28,   4,   0]])

In [73]:
#Importing Decision Tree
from sklearn.tree import DecisionTreeClassifier

In [64]:
model = DecisionTreeClassifier()

In [65]:
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [66]:
print("Accuracy = ", model.score(X_test, y_test)*100)

Accuracy =  78.77094972067039

In [72]:
print("Predict value " + str(model.predict([X[5]])))
print("Real value " + str(y[5]))

Predict value [0]
Real value 0